### ISSUE TITLE
UnboundLocalError: local variable 'notebook' referenced before assignment

### ISSUE THREAD

**Issue by pplonski** [mljar/mercury#148]
There might be very mighty looking error message if there are some tasks with old notebooks.

```python
[2022-07-28 11:17:14,676: ERROR/MainProcess] Task apps.tasks.tasks.task_execute[d9904836-2f1a-4f38-8d6d-69f1999dc13d] raised unexpected: UnboundLocalError("local variable 'notebook' referenced before assignment")
Traceback (most recent call last):
  File "/home/piotr/sandbox/bloxs_test/blox_test_env/lib/python3.8/site-packages/mercury/apps/tasks/tasks.py", line 51, in task_execute
    task = Task.objects.get(pk=job_params["db_id"])
  File "/home/piotr/sandbox/bloxs_test/blox_test_env/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/piotr/sandbox/bloxs_test/blox_test_env/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
apps.tasks.models.Task.DoesNotExist: Task matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/piotr/sandbox/bloxs_test/blox_test_env/lib/python3.8/site-packages/mercury/apps/tasks/tasks.py", line 349, in task_execute
    task.result = str(e)
UnboundLocalError: local variable 'task' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/piotr/sandbox/bloxs_test/blox_test_env/lib/python3.8/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/piotr/sandbox/bloxs_test/blox_test_env/lib/python3.8/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/piotr/sandbox/bloxs_test/blox_test_env/lib/python3.8/site-packages/mercury/apps/tasks/tasks.py", line 356, in task_execute
    print(notebook.schedule)
UnboundLocalError: local variable 'notebook' referenced before assignment

```

**Comment by pplonski** [comment]
fixed in V2
