### ISSUE TITLE
Mercury Download PDF 'Browser closed unexpectedly:'

### ISSUE THREAD

**Issue by mgrevers** [mljar/mercury#164]
When running my Mercury application (application works fine, download HTML works fine), I want to download the PDF of my results. However, Mercury just cycles and returns an error message 'Browser closed unexpectedly:'. 

**I am running a Jupyter Notebook hosted on an EC2 server on my Mercury application.**

Any ideas why this might be happening?

Here is the full error output:

```
[2022-09-14 22:26:22,116: ERROR/MainProcess] Task apps.tasks.tasks_export.export_to_pdf[e5ac35ae-9fa0-4a37-939f-369a6a93d3dc] raised unexpected: BrowserError('Browser closed unexpectedly:\n')
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/lib/python3.9/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ec2-user/anaconda3/lib/python3.9/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ec2-user/anaconda3/lib/python3.9/site-packages/mercury/apps/tasks/tasks_export.py", line 40, in export_to_pdf
    to_pdf(notebook_os_path + slides_postfix, pdf_os_path)
  File "/home/ec2-user/anaconda3/lib/python3.9/site-packages/mercury/apps/tasks/export_pdf.py", line 129, in to_pdf
    pool.submit(
  File "/home/ec2-user/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/home/ec2-user/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/ec2-user/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ec2-user/anaconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/ec2-user/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/ec2-user/anaconda3/lib/python3.9/site-packages/mercury/apps/tasks/export_pdf.py", line 13, in html_to_pdf
    browser = await launch(
  File "/home/ec2-user/anaconda3/lib/python3.9/site-packages/pyppeteer/launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "/home/ec2-user/anaconda3/lib/python3.9/site-packages/pyppeteer/launcher.py", line 168, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/home/ec2-user/anaconda3/lib/python3.9/site-packages/pyppeteer/launcher.py", line 227, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:
```

**Comment by pplonski** [comment]
Do you have `pyppeteer` and `Chromium` installed on EC2? How have you done the deployment? Are you using `docker-compose.yml` or `docker-compose-pro.yml`? Do you have the latest version of Mercury (1.1.6)?
