### ISSUE TITLE
mercury run/watch fail to run any notebook. Possibly related to django/sqlite

### ISSUE THREAD

**Issue by yidaki53** [mljar/mercury#183]
Hi!

I am just trying to get mercury back up and running. It worked fine right after I installed it, but now it keeps giving me this error that I don't understand.

I am on Linux Debian, and I have Python 3.9, 3.10, and 2.7 installed.

It gives the same error no matter what I do, even when I run it from a clean Poetry environment.

Any help would be appreciated. 

```
$ mercury run demo.ipynb
                                                                                  
     _ __ ___   ___ _ __ ___ _   _ _ __ _   _ 
    | '_ ` _ \ / _ \ '__/ __| | | | '__| | | |
    | | | | | |  __/ | | (__| |_| | |  | |_| |
    |_| |_| |_|\___|_|  \___|\__,_|_|   \__, |
                                         __/ |
                                        |___/ 
        
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, django_drf_filepond, notebooks, sessions, tasks
Running migrations:
  No migrations to apply.

0 static files copied to '/home/robin/anaconda3/lib/python3.9/site-packages/mercury/static', 199 unmodified.
Traceback (most recent call last):
  File "/home/robin/anaconda3/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/robin/anaconda3/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: notebooks_notebook.share

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/robin/anaconda3/bin/mercury", line 8, in <module>
    sys.exit(main())
  File "/home/robin/anaconda3/lib/python3.9/site-packages/mercury/mercury.py", line 98, in main
    execute_from_command_line(["mercury.py", "add", run_add_notebook])
  File "/home/robin/anaconda3/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/robin/anaconda3/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/robin/anaconda3/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/robin/anaconda3/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/robin/anaconda3/lib/python3.9/site-packages/mercury/apps/notebooks/management/commands/add.py", line 17, in handle
    notebook_id = self.notebook_id_available(notebook_path)
  File "/home/robin/anaconda3/lib/python3.9/site-packages/mercury/apps/notebooks/management/commands/add.py", line 37, in notebook_id_available
    notebook = Notebook.objects.filter(path=os.path.abspath(notebook_path)).first()
  File "/home/robin/anaconda3/lib/python3.9/site-packages/django/db/models/query.py", line 674, in first
    for obj in (self if self.ordered else self.order_by('pk'))[:1]:
  File "/home/robin/anaconda3/lib/python3.9/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/home/robin/anaconda3/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/robin/anaconda3/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/robin/anaconda3/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/robin/anaconda3/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/robin/anaconda3/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/robin/anaconda3/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/robin/anaconda3/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/robin/anaconda3/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/robin/anaconda3/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/robin/anaconda3/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: notebooks_notebook.share
```

**Comment by pplonski** [comment]
Sorry @yidaki53 for problem. Looks like you upgraded Mercury and have an old database. I need to write code to handle that.

In the meantime, please remove the old database, it should be at (based on your logs):

```
rm /home/robin/anaconda3/lib/python3.9/site-packages/mercury/db.sqlite3
```

Mercury will automatically create a new database with new tables.

**Comment by yidaki53** [comment]
> Sorry @yidaki53 for problem. Looks like you upgraded Mercury and have an old database. I need to write code to handle that.
> 
> In the meantime, please remove the old database, it should be at (based on your logs):
> 
> ```
> rm /home/robin/anaconda3/lib/python3.9/site-packages/mercury/db.sqlite3
> ```
> 
> Mercury will automatically create a new database with new tables.

Ah, I see. Thank you for the swift response.

That worked like a charm!

**Comment by pplonski** [comment]
Great! May I ask, what are you building with Mercury?

(I'm working on V2 of Mercury, there will be cell caching and dynamic widgets!)

**Comment by pplonski** [comment]
I've added a new command:

```
mercury run clear
```

It deletes old sqlite database. It is available in Mercury V2, please read more at https://RunMercury.com
