### ISSUE TITLE
no widgets on website

### ISSUE THREAD

**Issue by jefke-glider** [mljar/mercury#213]
I installed the latest version (2.04)  on a server via docker. I also installed the mercury-demo-1 code, and refer to that in the configuration of mercury. The website seems to appear , but I don't see the widgets. I see some errors, don't know if it has something to do with it:
NB 2023-02-16 12:02:22,947 ------------Init widgets
NB 2023-02-16 12:02:22,947 {'purpose': <Purpose.InitWidgets: 'init-widgets'>, 'widgets': []}
NB 2023-02-16 12:02:22,947 Worker id=32 set state Running uuid f1a27a823d58
NB 2023-02-16 12:02:22,947 Worker id=32 exists
NB 2023-02-16 12:02:22,949 Send state Running
NB 2023-02-16 12:02:25,233 WS on_message {"purpose": "worker-ping"}
NB 2023-02-16 12:02:25,233 Porcess msg {"purpose": "worker-ping"}
NB 2023-02-16 12:02:25,233 Worker id=32 set state Running uuid f1a27a823d58
NB 2023-02-16 12:02:25,233 Worker id=32 exists
NB 2023-02-16 12:02:25,236 Send state Running
NB 2023-02-16 12:02:25,237 Worker id=32 exists
NB 2023-02-16 12:02:25,238 Send state Running
NB 2023-02-16 12:02:26,520 WS on_message {"purpose": "close-worker"}
NB 2023-02-16 12:02:26,520 Porcess msg {"purpose": "close-worker"}
NB 2023-02-16 12:02:26,520 Delete worker id=32
NB 2023-02-16 12:02:27,321 WS on_pong
NB 2023-02-16 12:02:27,321 Check worker id=32 is stale
NB 2023-02-16 12:02:27,323 Exception when check if worker id=32 is stale
Traceback (most recent call last):
  File "/app/mercury/apps/nbworker/db.py", line 131, in is_worker_stale
    self.worker = Worker.objects.get(pk=self.worker_id)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
apps.ws.models.Worker.DoesNotExist: Worker matching query does not exist.
NB 2023-02-16 12:02:27,323 Delete worker id=32
NB 2023-02-16 12:02:27,324 Worker id=32 is stale, quit
NB 2023-02-16 12:02:27,324 1 - goodbye
NB 2023-02-16 12:02:27,324 WS on_error, 1

**Comment by jefke-glider** [comment]
seems I installed older demo. I downloaded a new one and that seems to work
