### ISSUE TITLE
download as html not working

### ISSUE THREAD

**Issue by pplonski** [mljar/mercury#231]
UnicodeEncodeError: 'latin-1' codec can't encode character '\ue6c6' in position 232655: Body ('\ue6c6') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
```
 Traceback (most recent call last):
mercury-cloud-worker1-1  |   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
mercury-cloud-worker1-1  |     self.run()
mercury-cloud-worker1-1  |   File "/usr/lib/python3.8/threading.py", line 870, in run
mercury-cloud-worker1-1  |     self._target(*self._args, **self._kwargs)
mercury-cloud-worker1-1  |   File "/app/mercury/apps/nbworker/nb.py", line 109, in process_msgs
mercury-cloud-worker1-1  |     self.download_html()
mercury-cloud-worker1-1  |   File "/app/mercury/apps/nbworker/nb.py", line 435, in download_html
mercury-cloud-worker1-1  |     _, nb_url = self.sm.save_nb_html(nb_body)
mercury-cloud-worker1-1  |   File "/app/mercury/apps/storage/storage.py", line 182, in save_nb_html
mercury-cloud-worker1-1  |     response = requests.put(upload_url, nb_html_body)
mercury-cloud-worker1-1  |   File "/usr/lib/python3/dist-packages/requests/api.py", line 131, in put
mercury-cloud-worker1-1  |     return request('put', url, data=data, **kwargs)
mercury-cloud-worker1-1  |   File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
mercury-cloud-worker1-1  |     return session.request(method=method, url=url, **kwargs)
mercury-cloud-worker1-1  |   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
mercury-cloud-worker1-1  |     resp = self.send(prep, **send_kwargs)
mercury-cloud-worker1-1  |   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
mercury-cloud-worker1-1  |     r = adapter.send(request, **kwargs)
mercury-cloud-worker1-1  |   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
mercury-cloud-worker1-1  |     resp = conn.urlopen(
mercury-cloud-worker1-1  |   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
mercury-cloud-worker1-1  |     httplib_response = self._make_request(
mercury-cloud-worker1-1  |   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
mercury-cloud-worker1-1  |     conn.request(method, url, **httplib_request_kw)
mercury-cloud-worker1-1  |   File "/usr/lib/python3.8/http/client.py", line 1256, in request
mercury-cloud-worker1-1  |     self._send_request(method, url, body, headers, encode_chunked)
mercury-cloud-worker1-1  |   File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
mercury-cloud-worker1-1  |     body = _encode(body, 'body')
mercury-cloud-worker1-1  |   File "/usr/lib/python3.8/http/client.py", line 164, in _encode
mercury-cloud-worker1-1  |     raise UnicodeEncodeError(
mercury-cloud-worker1-1  | UnicodeEncodeError: 'latin-1' codec can't encode character '\ue6c6' in position 232655: Body ('\ue6c6') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

```

**Comment by pplonski** [comment]
Fix in commit https://github.com/mljar/mercury/commit/4db852b813898d5864ae8849ef3325997a022f38
