### ISSUE TITLE
Demo app fails to run.

### ISSUE THREAD

**Issue by pythonista-blitz** [mljar/mercury#232]
I am running demo.ipynb, it works fine on vsCode and Jupyter Lab, but when I run it on the app it fails with the error below. I can't figure out why, so I need some help.
<details>
<summary>Error Code</summary>

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/.local/lib/python3.10/site-packages/traitlets/traitlets.py:656, in TraitType.get(self, obj, cls)
    655 try:
--> 656     value = obj._trait_values[self.name]
    657 except KeyError:
    658     # Check for a dynamic initializer.

KeyError: 'layout'

During handling of the above exception, another exception occurred:

NotImplementedError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 name = mr.Text(label="What is you name?", value="Piotr")

File ~/.local/lib/python3.10/site-packages/mercury/widgets/text.py:19, in Text.__init__(self, value, label, rows)
     17     self.text.description = label
     18 else:
---> 19     self.text = ipywidgets.Textarea(value=value, description=label)
     20     WidgetsManager.add_widget(self.text.model_id, self.code_uid, self.text)
     21 display(self)

File ~/.local/lib/python3.10/site-packages/ipywidgets/widgets/widget_string.py:67, in _String.__init__(self, value, **kwargs)
     65 if value is not None:
     66     kwargs['value'] = value
---> 67 super().__init__(**kwargs)

File ~/.local/lib/python3.10/site-packages/ipywidgets/widgets/widget_description.py:35, in DescriptionWidget.__init__(self, *args, **kwargs)
     33     kwargs.setdefault('tooltip', kwargs['description_tooltip'])
     34     del kwargs['description_tooltip']
---> 35 super().__init__(*args, **kwargs)

File ~/.local/lib/python3.10/site-packages/ipywidgets/widgets/widget.py:504, in Widget.__init__(self, **kwargs)
    501 super().__init__(**kwargs)
    503 Widget._call_widget_constructed(self)
--> 504 self.open()

File ~/.local/lib/python3.10/site-packages/ipywidgets/widgets/widget.py:517, in Widget.open(self)
    515 """Open a comm to the frontend if one isn't already open."""
    516 if self.comm is None:
--> 517     state, buffer_paths, buffers = _remove_buffers(self.get_state())
    519     args = dict(target_name='jupyter.widget',
    520                 data={'state': state, 'buffer_paths': buffer_paths},
    521                 buffers=buffers,
    522                 metadata={'version': __protocol_version__}
    523                 )
    524     if self._model_id is not None:

File ~/.local/lib/python3.10/site-packages/ipywidgets/widgets/widget.py:615, in Widget.get_state(self, key, drop_defaults)
    613 for k in keys:
    614     to_json = self.trait_metadata(k, 'to_json', self._trait_to_json)
--> 615     value = to_json(getattr(self, k), self)
    616     if not drop_defaults or not self._compare(value, traits[k].default_value):
    617         state[k] = value

File ~/.local/lib/python3.10/site-packages/traitlets/traitlets.py:703, in TraitType.__get__(self, obj, cls)
    701     return self
    702 else:
--> 703     return self.get(obj, cls)

File ~/.local/lib/python3.10/site-packages/traitlets/traitlets.py:659, in TraitType.get(self, obj, cls)
    656     value = obj._trait_values[self.name]
    657 except KeyError:
    658     # Check for a dynamic initializer.
--> 659     default = obj.trait_defaults(self.name)
    660     if default is Undefined:
    661         warn(
    662             "Explicit using of Undefined as the default value "
    663             "is deprecated in traitlets 5.0, and may cause "
   (...)
    666             stacklevel=2,
    667         )

File ~/.local/lib/python3.10/site-packages/traitlets/traitlets.py:1872, in HasTraits.trait_defaults(self, *names, **metadata)
   1869         raise TraitError(f"'{n}' is not a trait of '{type(self).__name__}' instances")
   1871 if len(names) == 1 and len(metadata) == 0:
-> 1872     return self._get_trait_default_generator(names[0])(self)
   1874 trait_names = self.trait_names(**metadata)
   1875 trait_names.extend(names)

File ~/.local/lib/python3.10/site-packages/traitlets/traitlets.py:627, in TraitType.default(self, obj)
    625     return self.default_value
    626 elif hasattr(self, "make_dynamic_default"):
--> 627     return self.make_dynamic_default()
    628 else:
    629     # Undefined will raise in TraitType.get
    630     return self.default_value

File ~/.local/lib/python3.10/site-packages/ipywidgets/widgets/trait_types.py:365, in InstanceDict.make_dynamic_default(self)
    364 def make_dynamic_default(self):
--> 365     return self.klass(*(self.default_args or ()),
    366                       **(self.default_kwargs or {}))

File ~/.local/lib/python3.10/site-packages/ipywidgets/widgets/widget_layout.py:86, in Layout.__init__(self, **kwargs)
     83     for side in ['top', 'right', 'bottom', 'left']:
     84         kwargs.setdefault(f'border_{side}', border)
---> 86 super().__init__(**kwargs)

File ~/.local/lib/python3.10/site-packages/ipywidgets/widgets/widget.py:504, in Widget.__init__(self, **kwargs)
    501 super().__init__(**kwargs)
    503 Widget._call_widget_constructed(self)
--> 504 self.open()

File ~/.local/lib/python3.10/site-packages/ipywidgets/widgets/widget.py:535, in Widget.open(self)
    531         from ipykernel.comm import Comm
    533         return Comm(**kwargs)
--> 535 self.comm = create_comm(**args)

File ~/.local/lib/python3.10/site-packages/comm/__init__.py:27, in _create_comm(*args, **kwargs)
     22 def _create_comm(*args, **kwargs):
     23     """Create a Comm.
     24 
     25     This method is intended to be replaced, so that it returns your Comm instance.
     26     """
---> 27     raise NotImplementedError("Cannot ")

NotImplementedError: Cannot 
```

</details>

**Comment by pplonski** [comment]
Hi @pythonista-blitz,

Thank you for reporting the issue! Could you please attach the notebook code? Are you trying to use layout from ipywidgets?

**Comment by pythonista-blitz** [comment]
Sorry for the delay in replying. I was looking into this issue.
First of all, I lowered the python version and it worked. 3.7.12 worked and 3.10.6 gave me an error. I am not sure if it is version dependent or if the virtual environment has become too complex.
However, I have encountered another bug. Text does not change interactively when it is made into an application (perhaps a separate issue would be better).
Please check the attached ipynb file that I am currently running.
Thanks for the great framework.

```
# %%
import mercury as mr
app = mr.App(
    title="title",
    description="demo",
    show_code=True,
    continuous_update=False,
    )

# %%
import openai
import requests
import os

openai.api_key = os.environ["OPENAI_API_KEY"]
openai.organization = os.environ["OPENAI_ORG_ID"]

# %%
def generate_answer(prompt:str, temp:float, ppenalty:float):
  response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    temperature=temp,
    presence_penalty=ppenalty,
    max_tokens=300,
    messages=[
        {"role": "system", "content": prompt},
    ]
)

  return response

# %%
keyword = mr.Text(
    label="kw",
    rows=3
    )
temp = mr.Numeric(
    label="temp",
    value=0.7, min=0.0, max=1.0, step=0.1)
ppenalty = mr.Numeric(
    label="penalty",
    value=0.1, min=-2.0, max=2.0, step=0.1)
print(keyword.value)

# %%
prompt = f"""Say something about next.
{keyword.value}"""

# %%
mr.Markdown(f"""## Prompt

{prompt}
""")

# %%
response = generate_answer(prompt, temp.value, ppenalty.value)

# %%
message = response["choices"][0]["message"]["content"]
content = message

tokens = response["usage"]["total_tokens"]

# %%
mr.Markdown(f"""## Result 

{content}
""")

# %%
mr.Markdown(f"""
## Tokens
{tokens}
""")


```

**Comment by pythonista-blitz** [comment]
@pplonski Since continues_update=False, I am running it with the run button. It seems that the default values are loaded each time the button is pressed.

**Comment by pplonski** [comment]
Hi @pythonista-blitz,

Thank you for reporting the problem. I've just release version 2.1.3 with some fixes. I cant reproduce the problem you described locally. Below is animation with my try:
![Peek 2023-03-31 10-46](https://user-images.githubusercontent.com/6959032/229073674-f63c56ba-57bd-4416-8f6d-e050826cb300.gif)

Please try to update `mercury` package to the latest version, and if the problem still occurs, please let me know. 

Thank you for you help!

**Comment by pythonista-blitz** [comment]
I've figured out how to reproduce the phenomenon. Entering keywords with line breaks in a text box does not work. I wanted to specify multiple keywords, so I typed in Enter line breaks. That seems to be the cause. One line statement with \ n in it would execute fine.

By the way, mercury 2.1.3 wouldn't pass the "mercury run" with the following error.

<details>
<summary>Error Code</summary>

```
Traceback (most recent call last):
  File "home/usr/workspace/myApp/.venv/bin/mercury", line 8, in <module>
    sys.exit(main())
  File "home/usr/workspace/myApp/.venv/lib/python3.7/site-packages/mercury/mercury.py", line 115, in main
    execute_from_command_line(["mercury.py", "migrate", "-v", 0])
  File "home/usr/workspace/myApp/.venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "home/usr/workspace/myApp/.venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "home/usr/workspace/myApp/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "home/usr/workspace/myApp/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "home/usr/workspace/myApp/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "home/usr/workspace/myApp/.venv/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "home/usr/workspace/myApp/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 423, in check
    databases=databases,
  File "home/usr/workspace/myApp/.venv/lib/python3.7/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "home/usr/workspace/myApp/.venv/lib/python3.7/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "home/usr/workspace/myApp/.venv/lib/python3.7/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "home/usr/workspace/myApp/.venv/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "home/usr/workspace/myApp/.venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "home/usr/workspace/myApp/.venv/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "home/usr/workspace/myApp/.venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/kuroseii/.pyenv/versions/3.7.12/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "home/usr/workspace/myApp/.venv/lib/python3.7/site-packages/mercury/server/urls.py", line 11, in <module>
    from apps.storage.urls import storage_urlpatterns
  File "home/usr/workspace/myApp/.venv/lib/python3.7/site-packages/mercury/apps/storage/urls.py", line 3, in <module>
    from apps.storage.views.dashboardfiles import (
ModuleNotFoundError: No module named 'apps.storage.views'
```

**Comment by pplonski** [comment]
@pythonista-blitz thank you for your patience! There was missing directory in `apps.storage`. I fixed it. 

I confirm, there is a bug in text area, I can reproduce it. Working on fix now.

**Comment by pplonski** [comment]
Thank you @pythonista-blitz, it should be working now.

Please install latest version `2.1.7`. You might need to clean database locally between runs. Please run:

```
# clean database locally
mercury run clear
```
 
![Peek 2023-03-31 15-30](https://user-images.githubusercontent.com/6959032/229133774-148fc061-f2a8-4895-b469-ecbf1533172a.gif)

**Comment by pythonista-blitz** [comment]
Thx !!
