### ISSUE TITLE
Mercury keeps "Waiting for worker ..." when starting it in WSL

### ISSUE THREAD

**Issue by dehiker** [mljar/mercury#284]
Mercury keeps "Waiting for worker ..." when started in **WSL**, as shown in the image below. Any ideas? Thanks a lot for your time!
<img width="975" alt="1684640074388" src="https://github.com/mljar/mercury/assets/1631480/697d41b3-48cd-477f-92b3-1c3eba29705c">

Please note I got the output when "mercury run" in **WSL** terminal:
<details><summary>mercury run</summary>
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: x-www-browser: not found<br/>
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: firefox: not found<br/>
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: iceweasel: not found<br/>
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: seamonkey: not found<br/>
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: mozilla: not found<br/>
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: epiphany: not found<br/>
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: konqueror: not found<br/>
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: chromium-browser: not found<br/>
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: google-chrome: not found<br/>
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: www-browser: not found<br/>
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: links2: not found<br/>
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: elinks: not found<br/>
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: links: not found<br/>
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: lynx: not found<br/>
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: w3m: not found<br/>
xdg-open: no method available for opening 'http://127.0.0.1:8000'<br/>
</details>

Also while I tried to run with `--verbose` as [this issue](https://github.com/mljar/mercury/issues/283), I got this error:
<details><summary>mercury run --verbose</summary>
Traceback (most recent call last):<br/>
  File "/home/dh/.local/bin/celery", line 8, in <module><br/>
    sys.exit(main())<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/celery/__main__.py", line 15, in main<br/>
    sys.exit(_main())<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/celery/bin/celery.py", line 217, in main<br/>
    return celery(auto_envvar_prefix="CELERY")<br/>
  File "/home/dh/.conda/envs/mc0412/lib/python3.9/site-packages/click/core.py", line 1130, in __call__<br/>
    return self.main(*args, **kwargs)<br/>
  File "/home/dh/.conda/envs/mc0412/lib/python3.9/site-packages/click/core.py", line 1055, in main<br/>
    rv = self.invoke(ctx)<br/>
  File "/home/dh/.conda/envs/mc0412/lib/python3.9/site-packages/click/core.py", line 1657, in invoke<br/>
    return _process_result(sub_ctx.command.invoke(sub_ctx))<br/>
  File "/home/dh/.conda/envs/mc0412/lib/python3.9/site-packages/click/core.py", line 1404, in invoke<br/>
    return ctx.invoke(self.callback, **ctx.params)<br/>
  File "/home/dh/.conda/envs/mc0412/lib/python3.9/site-packages/click/core.py", line 760, in invoke<br/>
    return __callback(*args, **kwargs)<br/>
  File "/home/dh/.conda/envs/mc0412/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func<br/>
    return f(get_current_context(), *args, **kwargs)<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/celery/bin/base.py", line 134, in caller<br/>
    return f(ctx, *args, **kwargs)<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/celery/bin/worker.py", line 343, in worker<br/>
    worker = app.Worker(<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/celery/worker/worker.py", line 94, in __init__<br/>
    self.app.loader.init_worker()<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/celery/loaders/base.py", line 111, in init_worker<br/>
    self.import_default_modules()<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/celery/loaders/base.py", line 105, in import_default_modules<br/>
    raise response<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/celery/utils/dispatch/signal.py", line 276, in send<br/>
    response = receiver(signal=self, sender=sender, **named)<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/celery/fixups/django.py", line 82, in on_import_modules<br/>
    self.worker_fixup.validate_models()<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/celery/fixups/django.py", line 121, in validate_models<br/>
    run_checks()<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/django/core/checks/registry.py", line 88, in run_checks<br/>
    new_errors = check(app_configs=app_configs, databases=databases)<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/django/core/checks/urls.py", line 14, in check_url_config<br/>
    return check_resolver(resolver)<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/django/core/checks/urls.py", line 24, in check_resolver<br/>
    return check_method()<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/django/urls/resolvers.py", line 494, in check<br/>
    for pattern in self.url_patterns:<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__<br/>
    res = instance.__dict__[self.name] = self.func(instance)<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns<br/>
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__<br/>
    res = instance.__dict__[self.name] = self.func(instance)<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module<br/>
    return import_module(self.urlconf_name)<br/>
  File "/home/dh/.conda/envs/mc0412/lib/python3.9/importlib/__init__.py", line 127, in import_module<br/>
    return _bootstrap._gcd_import(name[level:], package, level)<br/>
  File "frozen importlib._bootstrap", line 1030, in _gcd_import<br/>
  File "frozen importlib._bootstrap", line 1007, in _find_and_load<br/>
  File "frozen importlib._bootstrap", line 986, in _find_and_load_unlocked<br/>
  File "frozen importlib._bootstrap", line 680, in _load_unlocked<br/>
  File "frozen importlib._bootstrap_external", line 850, in exec_module<br/>
  File "frozen importlib._bootstrap", line 228, in _call_with_frames_removed<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/mercury/server/urls.py", line 8, in <module><br/>
    from apps.notebooks.urls import notebooks_urlpatterns<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/mercury/apps/notebooks/urls.py", line 3, in <module><br/>
    from apps.notebooks.views import (<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/mercury/apps/notebooks/views.py", line 13, in <module><br/>
    from apps.notebooks.tasks import task_init_notebook, task_watch<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/mercury/apps/notebooks/tasks.py", line 27, in <module><br/>
    from apps.tasks.notify import validate_notify<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/mercury/apps/tasks/notify.py", line 8, in <module><br/>
    from apps.tasks.tasks_export import export_to_pdf<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/mercury/apps/tasks/tasks_export.py", line 7, in <module><br/>
    from apps.tasks.export_pdf import to_pdf<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/mercury/apps/tasks/export_pdf.py", line 8, in <module><br/>
    from pyppeteer import launch<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/pyppeteer/__init__.py", line 30, in <module><br/>
    from pyppeteer.launcher import connect, executablePath, launch, defaultArgs  # noqa: E402; noqa: E402<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/pyppeteer/launcher.py", line 26, in <module><br/>
    from pyppeteer.browser import Browser<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/pyppeteer/browser.py", line 11, in <module><br/>
    from pyee import EventEmitter<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/pyee/__init__.py", line 73, in <module><br/>
    from pyee._trio import TrioEventEmitter  # noqa<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/pyee/_trio.py", line 4, in <module><br/>
    import trio<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/trio/__init__.py", line 18, in <module><br/>
    from ._core import (<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/trio/_core/__init__.py", line 27, in <module><br/>
    from ._run import (<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/trio/_core/_run.py", line 2452, in <module><br/>
    from ._io_epoll import EpollIOManager as TheIOManager<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/trio/_core/_io_epoll.py", line 188, in <module><br/>
    class EpollIOManager:<br/>
  File "/home/dh/.local/lib/python3.9/site-packages/trio/_core/_io_epoll.py", line 189, in EpollIOManager<br/>
    _epoll = attr.ib(factory=select.epoll)<br/>
AttributeError: module 'select' has no attribute 'epoll'<br/>
</details>

**Comment by pplonski** [comment]
Hi @dehiker,

Thank you for reporting the issue. Looks like issue with installation. Do you have `mc0412` env in conda? It looks like you have env `mc0412` activated but installed the `mercury` package in system path?

Please try to install `mercury` once again:

```
conda install -c conda-forge -n mc0421 mercury
```

Please remember to set env name during installation.

**Comment by pplonski** [comment]
In the #283 I've added safer import of `pyppeteer` package which may cause this error. The changes will be in the next release - hopefully this week. Thank you!
