### ISSUE TITLE
Using ipyaggrid with mercury is not rendering the grid

### ISSUE THREAD

**Issue by gmouawad** [mljar/mercury#314]
Hello,

I created a cloud tenant of Mercury and I have added a grid using the Python library called ipyaagrid.
On my local jupyter notebook, the grid is displaying but on mercury the grid is not rendering. I added to my site files a requirements.txt file and I included ipyaagrid in it.

thanks

**Comment by pplonski** [comment]
I was checking this package last week. It will work after calling display on it. I will be back in the office in 1 hour, i will send you code example.

**Comment by gmouawad** [comment]
> I was checking this package last week. It will work after calling display on it. I will be back in the office in 1 hour, i will send you code example.

weird, I used a display call and it didnt render. OK thanks a lot appreciate it

**Comment by pplonski** [comment]
To use `ipyaggrid` in Mercury please use the following code for display:

```python
from IPython.display import HTML
HTML(g.export_html(build=True))
```

The `ipyaggrid` demo:
![ipyaggrid](https://github.com/mljar/mercury/assets/6959032/00fc83f9-0815-47a1-bcf6-8bd1351ed77d)

The alternative to `ipyaggrid` might be `itables` https://github.com/mwouts/itables

Demo of `itables`:
![itables](https://github.com/mljar/mercury/assets/6959032/a8b34d96-493f-47b1-b4f8-a65bce9a61b9)


@gmouawad if you found Mercury valuable please start a repository and share the information about the framework with your friends, so we can get more users. Thanks!

**Comment by gmouawad** [comment]
with ipyaggrid I am getting a js error on the mercury cloud:

[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'AgGridModel' from module 'ipyaggrid'
TypeError: Cannot read properties of undefined (reading 'AgGridModel')
    at https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:16:642643
    at async rl.loadModelClass (https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:16:329116)
    at async rl._make_model (https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:16:325601)

**Comment by pplonski** [comment]
I will check it. Is it working for you locally?

**Comment by gmouawad** [comment]
> I will check it. Is it working for you locally?

on my jupyter notebook yes, but local mercury is not yet ready due to an issue with the ssl as mentioned in issue #311

**Comment by pplonski** [comment]
Do you have Jupyter Notebook running on remote machine? If you are running Jupyter Notebook on your local machine then you can test app in Mercury with the command `mercury run`. It will start local dev server for you.

**Comment by gmouawad** [comment]
> Yes, please create a new issue. You need to install Chromium, it can be done with `pyppeteer-install` command. What operating system are you using?

Windows 10

**Comment by pplonski** [comment]
Im closing the issue. If you have still a problem please reopen.

**Comment by gmouawad** [comment]
> Im closing the issue. If you have still a problem please reopen.

Hi Piotr, yes the issue is still valid.

it shows an error once the notebook is implemented on the docker container
![image](https://github.com/mljar/mercury/assets/80507466/39f2b341-4242-461a-ac2e-9c722ee2a091)

**Comment by pplonski** [comment]
Is it working locally? Do you have problem only in docker environment?


Why would you like to use `ipyaggrid`? I was testing recenlty `itables` package, and it was working very good with Mercury. Do you need any special feature from `ipyaggrid`?

**Comment by gmouawad** [comment]
> 

I was testing it. It is not working on the cloud tenant nor docker.

I will check itable

**Comment by gmouawad** [comment]
@pplonski I want a grid that has sorting and filtering on a column level, itable doesn't have the filtering capability. or at least I couldn't do it

**Comment by pplonski** [comment]
New version of Mercury fully support all ipywidgets 👍
