### ISSUE TITLE
Some really bad error

### ISSUE THREAD

**Issue by aplonska** [mljar/mercury#46]
Notebook is executed with errors.

2022-02-17 10:45:30.028511: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations: AVX2 FMA To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags. 2022-02-17 10:45:30.154158: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 155539800 exceeds 10% of free system memory. 2022-02-17 10:45:30.223060: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 155539800 exceeds 10% of free system memory. 2022-02-17 10:45:30.543504: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 143824140 exceeds 10% of free system memory. 2022-02-17 10:45:31.503299: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 575296560 exceeds 10% of free system memory. 2022-02-17 10:45:31.763055: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 575296560 exceeds 10% of free system memory. [NbConvertApp] ERROR | Kernel died while waiting for execute reply. Traceback (most recent call last): File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 949, in async_execute_cell exec_reply = await self.task_poll_for_reply asyncio.exceptions.CancelledError During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/bin/jupyter-nbconvert", line 8, in <module> sys.exit(main()) File "/usr/local/lib/python3.8/dist-packages/jupyter_core/application.py", line 264, in launch_instance return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs) File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 846, in launch_instance app.start() File "/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py", line 361, in start self.convert_notebooks() File "/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py", line 533, in convert_notebooks self.convert_single_notebook(notebook_filename) File "/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py", line 498, in convert_single_notebook output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer) File "/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py", line 427, in export_single_notebook output, resources = self.exporter.from_filename(notebook_filename, resources=resources) File "/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/exporter.py", line 186, in from_filename return self.from_file(f, resources=resources, **kw) File "/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/exporter.py", line 204, in from_file return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw) File "/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/html.py", line 145, in from_notebook_node return super().from_notebook_node(nb, resources, **kw) File "/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/templateexporter.py", line 376, in from_notebook_node nb_copy, resources = super().from_notebook_node(nb, resources, **kw) File "/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/exporter.py", line 143, in from_notebook_node nb_copy, resources = self._preprocess(nb_copy, resources) File "/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/exporter.py", line 323, in _preprocess nbc, resc = preprocessor(nbc, resc) File "/usr/local/lib/python3.8/dist-packages/nbconvert/preprocessors/base.py", line 47, in __call__ return self.preprocess(nb, resources) File "/usr/local/lib/python3.8/dist-packages/nbconvert/preprocessors/execute.py", line 84, in preprocess self.preprocess_cell(cell, resources, index) File "/usr/local/lib/python3.8/dist-packages/nbconvert/preprocessors/execute.py", line 105, in preprocess_cell cell = self.execute_cell(cell, index, store_history=True) File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 84, in wrapped return just_run(coro(*args, **kwargs)) File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 62, in just_run return loop.run_until_complete(coro) File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete return future.result() File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 953, in async_execute_cell raise DeadKernelError("Kernel died") nbclient.exceptions.DeadKernelError: Kernel died

**Comment by Thijss** [comment]
Perhaps you ran out of memory?
> Allocation of 155539800 exceeds 10% of free system memory.

**Comment by pplonski** [comment]
@Thijss you are right! The error was while running on Heroku free dyno. Thank you!
